services:
    lingostruct.api:
        image: lingostruct
        env_file: .env
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "${APPLICATION_PORT}:${APPLICATION_PORT}"
        environment:
            DATABASE_HOST: lingostruct.postgres
            DATABASE_PORT: 5432
            REDIS_HOST: lingostruct.redis
            REDIS_PORT: 6379
        depends_on:
            lingostruct.postgres:
                condition: service_healthy
            lingostruct.redis:
                condition: service_healthy
    lingostruct.postgres:
        image: postgres:18
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
        volumes:
            - postgres_data:/var/lib/postgresql
        ports:
            - "${DATABASE_PORT}:5432"
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}",
                ]
            interval: 5s
            timeout: 5s
            retries: 5

    lingostruct.redis:
        image: redis:8-alpine
        restart: always
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - redis_data:/data
        healthcheck:
            test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping"]
            interval: 5s
            timeout: 3s
            retries: 5
        ports:
            - "${REDIS_PORT}:6379"

volumes:
    postgres_data:
    redis_data:
